# Generated by Django 4.1.4 on 2023-02-03 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0002_peliculas_premios_series_delete_alumno_delete_curso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premios',
            old_name='pelicula_serie',
            new_name='pelicula',
        ),
    ]
