# Generated by Django 4.1.4 on 2023-02-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0003_rename_pelicula_serie_premios_pelicula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='cantidad_de_capitulos',
        ),
    ]
